### ISSUE TITLE
Suggest Password Feature, Update Readme

### ISSUE THREAD

**Issue by iamajitsingh** [hellomlorg/django-login-logout#6]
Enhancement can be made to the system, i.e. while signing up user can either add their own password or we can suggest it to them.
Also styling needs to be done at least to a basic level.
Readme needs updating to the latest features
@vishnureddys

**Comment by vishnusreddy** [comment]
What does suggest password mean? Are you recommending a secure password comprising random characters?

Is this similar to the password suggested by Google Chrome?

**Comment by iamajitsingh** [comment]
Yeah, but over here the user can set the complexity (If they want special characters, etc. to be included)

**Comment by vishnusreddy** [comment]
Amazing. I'll check it out and merge it if everything works.

**Comment by vishnusreddy** [comment]
Done. I've merged it. Just noticed something. Can you please change the capital L in the **L**ogin folder? From what I know it is a better practice to keep them in lower case.

**Comment by iamajitsingh** [comment]
Addressed in #8.
